#!/usr/bin/env bash
set -Eueo pipefail

SKIP_UPDATE=0
if [ $# -ge 1 ] && [ "$1" = "--skip-update" ]; then
  SKIP_UPDATE=1
fi

if [ $SKIP_UPDATE = 0 ]; then
  sudo apt update
  sudo apt -y upgrade
  git pull --rebase --autostash
fi

PACKAGES=(
  apt-transport-https
  ca-certificates
  software-properties-common
  make
  screenfetch
  curl
  wget
  unzip
)

for pkg in "${PACKAGES[@]}"; do
  [ ! $(dpkg -s $pkg >/dev/null 2>&1;) ] || sudo apt -y install $pkg
done

# Find the installers and run them iteratively
find . -name install.sh | while read installer ; do sh -c "${installer}" ; done

if [ $SKIP_UPDATE = 0 ]; then
  sudo apt -y autoremove
  sudo apt -y clean
fi

echo "Job's done!"
